# Generated by Django 3.0.6 on 2020-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='setting_weekstart',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='setting_dayend',
            field=models.DecimalField(decimal_places=0, default=24, max_digits=2),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='setting_daystart',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
