# Generated by Django 3.0.6 on 2020-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='plan',
            field=models.CharField(default='starter', max_length=40),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='renewal_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='signup_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
