# Generated by Django 3.0.6 on 2020-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200619_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent'), ('visitor', 'Visitor')], default='admin', max_length=16),
        ),
    ]
