# Generated by Django 3.0.6 on 2020-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200630_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
