# Generated by Django 3.0.6 on 2020-06-14 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200614_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
