# Generated by Django 3.0.6 on 2020-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200619_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contract_type',
            field=models.CharField(choices=[('hour', 'Paid by the hour'), ('fix', 'Fix contract')], default='admin', max_length=16),
        ),
    ]
