# Generated by Django 3.0.6 on 2020-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200630_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
