# Generated by Django 3.0.6 on 2020-06-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200610_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='county',
            new_name='company_name',
        ),
    ]
