# Generated by Django 3.0.6 on 2020-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200610_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='renewal_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
