# Generated by Django 3.0.6 on 2020-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20200612_2239'),
        ('profiles', '0010_agentrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentRole',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
