# Generated by Django 3.0.6 on 2020-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('training', 'Training'), ('meeting', 'Meeting'), ('holidays', 'Holidays'), ('sick', 'Sick'), ('Leave', 'leave'), ('lunch', 'Lunch break'), ('dinner', 'Dinner break'), ('break', 'Paid break'), ('absence', 'Absence')], max_length=16),
        ),
    ]
