# Generated by Django 3.0.6 on 2020-06-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='agent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.AgentRole'),
        ),
    ]
