# Generated by Django 3.0.6 on 2020-06-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=80)),
                ('role_color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='Teamname', max_length=64)),
                ('planning_deadline', models.IntegerField(default=0)),
                ('coaching_rep', models.IntegerField(default=0)),
                ('min_lunchbreak', models.IntegerField(default=30)),
                ('min_dinnerbreak', models.IntegerField(default=30)),
                ('min_paidbreak', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=64)),
                ('weekday', models.IntegerField(default=0)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Team')),
            ],
        ),
    ]
