# Generated by Django 3.0.6 on 2020-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200619_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrole',
            name='team',
        ),
        migrations.AlterField(
            model_name='agentrole',
            name='role_color',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='agentrole',
            name='role_name',
            field=models.CharField(max_length=64),
        ),
    ]
